<?php
/**
 * @category    MT
 * @package     MT_Filter
 * @copyright   Copyright (C) 2008-2013 YesTheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      YesTheme.com
 * @email       support@yestheme.com
 */
?>
<?php $barColor = Mage::helper('mtfilter')->getConfig('mtfilter/general/bar_color') ?>
<style type="text/css">
    #nprogress .bar {
        background: #<?php echo $barColor?>;
    }
    #nprogress .peg {
        box-shadow: 0 0 15px #<?php echo $barColor?>, 0 0 10px #<?php echo $barColor?>;
    }
</style>
<script type="text/javascript">
    window.mtFilter = new MTFilter('mtFilter', <?php echo Mage::helper('mtfilter')->getConfig()?>);
</script>