<!-- navigation BOF -->
<?php 
$megaeffect = Mage::getStoreConfig('mtbrave/menu/effect');
$_menu = $this->renderCategoriesMenuHtml(FALSE, 0, 'level-top', 'sub-wrapper' );
$routeName = Mage::app()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier(); 
 
?>
<div class="mt-menu mt-effect-slide">
    <div class="mt-menu-title">
        <div class="navbar visible-xs">
            <div class="navbar navbar-inverse">
                <div class="navbar-header">
                    <div class="navbar-toggle" type="button" data-toggle="collapse">
                        <div class="icon-title pull-left">
                            <span class="sr-only"><?php echo $this->__('MENU');?></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </div>
                        <span class="title"><?php echo $this->__('MENU');?></span>
                        <button class="icon-close" type="button"></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar clearfix">
        <ul id="mt_accordionmenu" class="nav-accordion nav-mobile-accordion">
            <li><a href="<?php echo $this->getBaseUrl(); ?>"><?php echo $this->__('Home'); ?></a></li>
            <?php echo $this->renderCategoriesMenuHtml(TRUE, 0, 'level-top'); ?>
        </ul>
        <script type="text/javascript">
            $mt(document).ready(function() {
                $mt("#mt_accordionmenu").mtAccordionMenu({
                    accordion:true,
                    speed: 400,
                    closedSign: 'collapse',
                    openedSign: 'expand',
                    mouseType: 0,
                    easing: 'easeInOutQuad'
                });
            });
        </script>
    </div>
</div>
<div class="site-overlay"></div>
