<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2013 YesTheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      YesTheme.com
 * @email       support@yestheme.com
 */
?>
<?php
$attributes = $this->getAttibuteOptions();
$id         = $this->getConfig('id');
$column     = $this->getConfig('column');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
?>
<?php if ($scroll == 1):?>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            var itemsCount = getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'column');
            jQuery('#<?php echo $id?>').flexslider({
                namespace: '<?php echo $this->getConfig('namespace')?>',
                slideshow: <?php echo $this->getConfig('autoplay')?>,
                slideshowSpeed: <?php echo $this->getConfig('speed')?>,
                animationLoop: <?php echo $this->getConfig('loop')?>,
                controlNav: <?php echo $this->getConfig('paging')?>,
                animation: "slide",
                itemWidth: getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'width'),
                itemMargin: 0,
                minItems: itemsCount,
                maxItems: itemsCount,
                controlsContainer: "#nav-wrapper-<?php echo $_id ?>",
                selector: ".slides > .slide",
                onResize: function(slider){
                    var itemsCount = getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'column');
                    slider.vars.minItems = itemsCount;
                    slider.vars.maxItems = itemsCount;
                }
            });
        });
    </script>
<?php endif ?>
<div class="slider-attribute-wrapper<?php echo $scroll==1 ? ' flexslider' : ''?>" id="<?php echo $id ?>">
    <div class="block-container">
        <div class="row show-grid">
            <?php if ($title){?>
            <div class="col-lg-10">
                <h3 class="pull-left block-title">
                    <strong class="no-padding-l">
                        <?php echo $title?>
                    </strong>
                </h3>
            </div>
            <?php }?>
            <div class="col-lg-2">
                <div id="nav-wrapper-<?php echo $_id ?>" class="nav-wrapper pull-right">&nbsp;</div>
            </div>
        </div>
    </div>
    <ul class="slides">
        <?php foreach ($attributes as $attribute): ?>
            <li class="slide">
                <a href="<?php echo $attribute['link'] ?>" title="<?php echo Mage::helper('mtwidget')->__('%s', $attribute['label']) ?>">
                    <img src="<?php echo strpos($attribute['image'], 'http') === 0 ? $attribute['image'] : Mage::getBaseUrl('media') . $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" />
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</div>
<style>
    .attribute-slider-wrapper .slide {text-align: center}
    .attribute-slider-wrapper .slide a {margin: 2px; display: inline-block}
</style>